version: '3.7'
services:

  dashboard:
    build: 
      context: ./
    container_name: ${COMPOSE_PROJECT_NAME}_dashboard
    hostname: ${COMPOSE_PROJECT_NAME}_dashboard
    restart: always
    ports:
      - 5000:80
    volumes:
      - ./certs:/etc/letsencrypt

  # certbot:
  #   container_name: "certbot"
  #   image: certbot/certbot
  #   volumes:
  #     - .:/letsencrypt
  #     - ./certs:/etc/letsencrypt
  #   command: certonly --webroot -w /letsencrypt -d app2.ouicodedata.com -d www.app2.ouicodedata.com --force-renew --agree-tos --email pfpimenta@gmail.com
  #   depends_on:
  #     - dashboard