version: '3'

services:
  webserver:
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    restart: always
    volumes:
      - ./docker/nginx/nginx.conf/:/etc/nginx/conf.d/default.conf
      - .:/letsencrypt # for certboot challenges
      - ./certs:/etc/letsencrypt # for letsencrypt certificates
      - ./etc/ssl/certs:/etc/ssl/certs
  certbot:
    image: certbot/certbot
    volumes:
      - .:/letsencrypt
      - ./certs:/etc/letsencrypt