version: '3'
services:
  web:
    build: ./

  # certbot:
  #   container_name: "certbot"
  #   image: certbot/certbot
  #   volumes:
  #     - .:/letsencrypt
  #     - ./certs:/etc/letsencrypt
  #   command: certonly --webroot -w /letsencrypt -d app2.ouicodedata.com -d www.app2.ouicodedata.com --force-renew --agree-tos --email pfpimenta@gmail.com
  #   depends_on:
  #     - dashboard