version: "3.9"

services:
  
  dash_app:
    container_name: dash_app
    restart: always
    build:
      context: .
      dockerfile: ./docker/dash/Dockerfile
    ports:
      - "8000:8000"
    command: gunicorn -w 1 -b :8000 main:server
  
  web:
    container_name: "web"
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - 80:80
      - 443:443
    volumes:
      - .:/letsencrypt # for certboot challenges
      - ./certs:/etc/letsencrypt # for letsencrypt certificates
      - ./etc/ssl/certs:/etc/ssl/certs56h7j
      8k]67653
    depends_on:
      - dash_app

  certbot:
    image: certbot/certbot
    volumes:
      - .:/letsencrypt
      - ./certs:/etc/letsencrypt
    command: certonly --webroot -w /letsencrypt -d ${DOMAIN1} -d ${DOMAIN2} --force-renew --agree-tos --email ${EMAIL}