version: "3.9"

services:
  web:
    container_name: "web"
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - 80:80
      - 443:443
    volumes:
      - .:/letsencrypt # for certboot challenges
      - ./certs:/etc/letsencrypt # for letsencrypt certificates
    #  - ./etc/ssl/certs:/etc/ssl/certs
  certbot:
    image: certbot/certbot
    volumes:
      - .:/letsencrypt
      - ./certs:/etc/letsencrypt
    command: certonly --webroot -w /letsencrypt -d app2.ouicodedata.com -d www.app2.ouicodedata.com --force-renew --agree-tos --email pfpimenta@gmail.com
